//
//
//  Generated by StarUML(tm) Java Add-In
//





public class Animal {
	public String name;
	public Boolean callDoctor;
	public Boolean disease;
	public void animal(string d:boolean n) {
	
	}
	
	public void getAil(boolean Disease) {
	
	}
	
	public void toCallDoctor() {
	
	}
}
