//
//
//  Generated by StarUML(tm) Java Add-In
//





public class Animal {
	public String Name;
	public Boolean CallDoctor;
	public Boolean Disease;
	public void Animal(string d:boolean n) {
	
	}
	
	public void getAil(boolean Disease) {
	
	}
	
	public void ToCallDoctor() {
	
	}
}
