//
//
//  Generated by StarUML(tm) Java Add-In
//





public class Aviary {
	public String Name;
	public Menu MenuForDay;
	public String TypeAnimals;
	public ScheduleVaccination Schedule;
	public boolean TimeToFeed;
	public int NumberFeeding;
	public Animal ListAnimal;
	public void Aviary() {
	
	}
	
	public void PrintAviary() {
	
	}
	
	public void PrintListAnimal() {
	
	}
	
	
}
