//
//
//  Generated by StarUML(tm) Java Add-In
//





public class Aviary {
	public String name;
	public Menu menuForDay;
	public String typeAnimals;
	public ScheduleVaccination schedule;
	public boolean timeToFeed;
	public int numberFeeding;
	public Animal listAnimal;
	public void aviary() {
	
	}
	
	public void printAviary() {
	
	}
	
	public void printListAnimal() {
	
	}
	
	
}
