//
//
//  Generated by StarUML(tm) Java Add-In
//





public class Food {
	public String name;
	public int amountOnWarehouse;
	public int minAmount;
	public String typeFood;
	public int maxAmount;
	public void addFood(int incoming) {
	
	}
	
	public void subtractFood(int expenditure) {
	
	}
	
	public void checkAmount() {
	
	}
	
	public void orderFood() {
	
	}
}
