//
//
//  Generated by StarUML(tm) Java Add-In
//





public class Food {
	public String Name;
	public int AmountOnWarehouse;
	public int MinAmount;
	public String TypeFood;
	public int MaxAmount;
	public void AddFood(int incoming) {
	
	}
	
	public void SubtractFood(int expenditure) {
	
	}
	
	public void CheckAmount() {
	
	}
	
	public void OrderFood() {
	
	}
}
