//
//
//  Generated by StarUML(tm) Java Add-In
//





public class Menu {
	public Food ListFood;
	public int AmountFood;
	public void Menu() {
	
	}
	
	public void TakeFood() {
	
	}
	
	public void PrintMenu() {
	
	}
}
