//
//
//  Generated by StarUML(tm) Java Add-In
//





public class Menu {
	public Food listFood;
	public int amountFood;
	public void menu() {
	
	}
	
	public void takeFood() {
	
	}
	
	public void printMenu() {
	
	}
}
