//
//
//  Generated by StarUML(tm) Java Add-In
//





public class Reminder {
	public Food foodForBuy;
	public Vaccination vaccinaForBuy;
	public void printReminder() {
	
	}
	
	public void checkReminder() {
	
	}
}
