//
//
//  Generated by StarUML(tm) Java Add-In
//





public class Reminder {
	public Food FoodForBuy;
	public Vaccination VaccinaForBuy;
	public void PrintReminder() {
	
	}
	
	public void CheckReminder() {
	
	}
}
