//
//
//  Generated by StarUML(tm) Java Add-In
//





public class ScheduleVacination {
	public Vaccination listVaccination;
	public int amountVacination;
	public void scheduleVaccination() {
	
	}
	
	public void giveVaccination() {
	
	}
	
	public void addNewVaccination() {
	
	}
}
