//
//
//  Generated by StarUML(tm) Java Add-In
//





public class ScheduleVacination {
	public Vaccination ListVaccination;
	public int AmountVacination;
	public void ScheduleVaccination() {
	
	}
	
	public void giveVaccination() {
	
	}
	
	public void AddNewVaccination() {
	
	}
}
