//
//
//  Generated by StarUML(tm) Java Add-In
//





public class Vaccination {
	public String name;
	public Date NextData;
	public int frequency;
	public int amountOnWarehouse;
	public int maxAmount;
	public int minAmount;
	public void vaccination() {
	
	}
	
	public void orderVaccination() {
	
	}
}
