//
//
//  Generated by StarUML(tm) Java Add-In
//





public class Vaccination {
	public String Name;
	public Date NextData;
	public int Frequency;
	public int AmountOnWarehouse;
	public int MaxAmount;
	public int MinAmount;
	public void Vaccination() {
	
	}
	
	public void OrderVaccination() {
	
	}
}
