//
//
//  Generated by StarUML(tm) Java Add-In
//





public class Warehouse {
	public Food StorageFood;
	public Vaccination StorageVaccination;
	public void PrintStorageFood() {
	
	}
	
	public void AddNewFood() {
	
	}
	
	public void DeleteFood() {
	
	}
	
	public void AddNewVaccination() {
	
	}
	
	public void DeleteVaccination() {
	
	}
}
