//
//
//  Generated by StarUML(tm) Java Add-In
//





public class Warehouse {
	public Food storageFood;
	public Vaccination storageVaccination;
	public void printStorageFood() {
	
	}
	
	public void addNewFood() {
	
	}
	
	public void deleteFood() {
	
	}
	
	public void addNewVaccination() {
	
	}
	
	public void deleteVaccination() {
	
	}
}
